# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cba7613e1a63d2f5deecb4bb09f8fddbc63749dfa3908f44c8e02c8e48cd7da5ab853912f296665ffc5a7ace44b9c97053f47bc9d641ef0904ae5d1dc3c1070e

test:
  secret_key_base: 58ba340581ccfd010ae85112865a8fa206e746e90b5f5a54afc944f67b5a44875e371c7fb4956ed40accae9b8d3fe3f9b4e92a435e723cbba3c21d73a9d41566

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
